FROM blacktop/kibana-plugin-builder:node

LABEL maintainer "https://github.com/blacktop"

ENV LANG=C.UTF-8
ENV JAVA_HOME=/usr/lib/jvm/default-jvm/jre
ENV PATH=${PATH}:${JAVA_HOME}/bin:/home/kibana/kibana/bin:${PATH}

RUN apk add --no-cache git openjdk8-jre ca-certificates bash

RUN npm install -g sao template-kibana-plugin

WORKDIR /home/kibana/kibana

# COPY config/kibana.dev.yml /home/kibana/kibana/config/kibana.dev.yml

EXPOSE 5601

USER node

CMD ["npm", "run", "elasticsearch"]
